version: "3"

services:
  manager:
    image: golang:1.14
    volumes:
      - .:/go/src/github.com/apisix/manager-api
    working_dir: /go/src/github.com/apisix/manager-api
    command: go test -v github.com/apisix/manager-api/service
